### ISSUE TITLE
No module named 'shared_utils.util'

### ISSUE THREAD

**Issue by hrppl** [aschalkamp/UKBBprodromalPD#1]
Hello! Thanks for your work, I get such an error when importing ukbb_parser, do you have any suggestions?

**Comment by aschalkamp** [comment]
Hi,

It might be that when you downloaded ukbb_parser from GitHub that you did not import all dependencies. ’Shared_utils’ is another repository that is used by ukbb_parser. Search for how to import submodules, that should sort it.

On 20 Dec 2023, at 14:31, hrppl ***@***.******@***.***>> wrote:

External email to Cardiff University - Take care when replying/opening attachments or links.
Nid ebost mewnol o Brifysgol Caerdydd yw hwn - Cymerwch ofal wrth ateb/agor atodiadau neu ddolenni.




Hello! Thanks for your work, I get such an error when importing ukbb_parser, do you have any suggestions?

**Comment by hrppl** [comment]
Thanks
